version: '3'
services: 
  lmi-api: 
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    restart: unless-stopped
    stop_grace_period: "3s"
    image: "${IMAGE_NAME}:${SERVER_VERSION}"
    ports:
      - "${DOCKER_WEB_PORT_FORWARD}:${APPLICATION_WEB_PORT}"

    container_name: "${CONTAINER_NAME}"